name: Dependabot

on:
  schedule:
    - cron: '0 0 * * 1' # Run every Monday at midnight
  workflow_dispatch: # Add this line to enable manual triggering

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Check for updates
        uses: dependabot/dependabot-core@v2
        with:
          package-ecosystem: 'npm'
          directory: '/examples/module4/lesson2/design-tokens'
          interval: 'weekly'
