name: Publish to AWS CodeArtifact by woolf1717

on:
  workflow_dispatch:
    inputs:
      version-type:
        description: 'Version type'
        required: true
        default: 'minor'
        type: choice
        options:
          - major
          - minor
          - patch

env:
  AWS_CA_TOKEN: ${{ secrets.AWS_CA_TOKEN }}
  AWS_CA_REGION: eu-central-1
  AWS_CA_DOMAIN: woolf1717
  AWS_CA_REPOSITORY: woolf1717
  AWS_CA_DOMAIN_OWNER: '021891611839'
  LIB_PACKAGEJSON_DIR: examples/module4/lesson2/design-tokens
  NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Build library
        working-directory: ${{ env.LIB_PACKAGEJSON_DIR }}
        run: |
          npm install
          npm install vitest@latest
          npm ci
          npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_CA_REGION }}

      - name: Refresh AWS CodeArtifact Token (if needed)
        uses: ./.github/actions/refresh-token
        with:
          gh-token: ${{ secrets.GH_REPO_ACCESS_TOKEN }}
          ca-token-expiration-time: ${{ secrets.AWS_CA_TOKEN_EXPIRATION_TIME }}
          ca-domain: ${{ env.AWS_CA_DOMAIN }}
          ca-domain-owner: ${{ env.AWS_CA_DOMAIN_OWNER }}

      - name: 'Automated Version Bump'
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_REPO_ACCESS_TOKEN }}
          PACKAGEJSON_DIR: ${{ env.LIB_PACKAGEJSON_DIR }}
        with:
          version-type: ${{ github.event.inputs.version-type }}

      - name: Publish to registry
        working-directory: ${{ env.LIB_PACKAGEJSON_DIR }}
        run: |
          REGISTRY_BASE_URL="${{ env.AWS_CA_DOMAIN }}-${{ env.AWS_CA_DOMAIN_OWNER }}.d.codeartifact.${{ env.AWS_CA_REGION }}.amazonaws.com/npm/${{ env.AWS_CA_REPOSITORY }}/"
          npm config set registry "https://$REGISTRY_BASE_URL"
          npm set "//$REGISTRY_BASE_URL:_authToken=eyJ2ZXIiOjEsImlzdSI6MTcyNjkxNTEwNiwiZW5jIjoiQTEyOEdDTSIsInRhZyI6Ik0zSVd4aGk3MTkzLTBxVk5CS0hjdUEiLCJleHAiOjE3MjY5NTgzMDYsImFsZyI6IkExMjhHQ01LVyIsIml2IjoibFVvVDQ5RTNWZjhJTWkxSyJ9.7su0Qs4uQsU_NvJeN7YpCg.-SNGC2IUtOeQ5RLQ.uiStxSo2d7CUiP3HC_LaWsx2Vrzktr-yzJX9BpphP6vBnSNX_f5DVbxnjfZeY_BlxoVsNBaYlTykL1oVqQBkl-ENtn6jdzLXjvFzCkUBPsespaQlnFcyYzeHZYmz74ugGz5Nh7F4qt-uOfbCAb07cUViXNwqKBGlgdwjHbz-GBBobyHPbwZ_mFyYaLbHwksbSuxryTHSLxrAPluAgc1Mimz_mfb41BpK04bWqPwwbCJ7p7RGK4FkTNzo40mNH13HhGPtScuOxKFCEMzmp5hx-j_l-B4PcsMZKBJ0brdEbyV0xV9J0HO5QVv_GeIm2XAVWZTkdTCK0Ccyc-k4HHvzAzeawAVaq6Yd504fOGY2oIhTrci9tS9PnneQddjfzfjam1rR8VcF2frEIlvgW0jMMstA41epup6Wy7ucObGQs0ttxRuqnhnG7cMeSUiubVHZZ4j-H3cWZIA8Y2iStkR3b_P0HVu52Ms-9dVj5xSBQtqCFcN_So-pSeXdQZ24EoSlzdtd-vZY9mvpzTuDr8g8xfSPLhNE8ROpvYUNNaAhkdp015FiryhMkOAntvDBgt9Y0W66dXgWbFoRqgnZS_OvMpaoAzKyD9Nuch5qy8DaIAX3zldmj1olof2wa7hDjr7JNW7Ca8wCFK-TWEwxTsGitYcFQSzcItLElMGlBqG9T3SSBHRFza_YkZZJ1qUSeh6berHvmUhWeTTnVaUh3wfJqjUeLkYHR936yUoq_cQp7EsbDUcsizRvimGJF-yHueO0594Gzcb0FSo9asDGDr-WZ3uChPfQYqK_y89JAtYltWpkZgC91g8vjO2NxN8enGZTzpJ-5EQso3xxan7LByfrlOch43KC3N0sJQobAbO1qjetsJ5cDIhk5UZEpw05hCm5yblbI4_9FHrsCQXDvBTVX2GmHxGHpsCQn41cHRWdoYEaj494H3O4Nr2LebrboXFmfrYkYuxt7IWr3u4LArTYscfKaxA5svBc.CSAcuEkJiFuknQqb7tSmYw"

          npm publish
